### ISSUE TITLE
pdfsizeopt corrupts bilevel images that are NOT black and white

### ISSUE THREAD

**Issue by rbrito** [pts/pdfsizeopt#101]
Dear @pts,

While optimizing some files, I found a very intriguing case of where pdfsizeopt corrupts the output. If an image had `BitsPerComponent` equals to 1, but it is not black and white (e.g, it is indexed, but with the specification of the index outside of the image, in a PDF dictionary) **and** one uses jbig2 as one of the compressors, then the output pdf becomes corrupted.

I am attaching:

1. The original PNG file.
2. A PDF file that was generated by img2pdf from the PNG file.
3. The output PDF generated by pdfsizeopt when called with the option `--use-image-optimizer=jbig2`.

This figure was extracted from a book from O'Reilly and I can send you privately the original offending page (in case it has other issues that I wasn't able to detect).

Thanks,

Rogério Brito.

![bar](https://user-images.githubusercontent.com/212145/48964558-58911680-ef91-11e8-9a72-dbe5cb3893a5.png)
[out.pdf](https://github.com/pts/pdfsizeopt/files/2612007/out.pdf)
[out.pso.pdf](https://github.com/pts/pdfsizeopt/files/2612008/out.pso.pdf)

**Comment by pts** [comment]
Thank you for reporting this! I was able to reproduce it with the latest pdfsizeopt:

```
$ pdfsizeopt --use-image-optimizer=jbig2 --do-generate-xref-stream=no --do-generate-object-stream=no --do-decompress-flate=yes out.pdf
info: This is pdfsizeopt rUNKNOWN size=393855.
info: prepending to PATH: ../pdfsizeopt_libexec
info: loading PDF from: out.pdf
info: loaded PDF of 1975 bytes
info: separated to 6 objs + xref + trailer
info: parsed 6 objs
info: found 0 Type1 fonts loaded
info: found 0 Type1C fonts loaded
info: will optimize image XObject 6; orig width=336 height=336 colorspace=/Indexed/DeviceRGB bpc=1 inv=False filter=/FlateDecode dp=1 size=1100 gs_device=png16m
info: saving PNG to psotmp.17385.img-6.parse.png
info: written 919 bytes to PNG
info: optimizing 1 images of 1100 bytes in total
info: executing image converter sam2p_np: sam2p -j:quiet -pdf:2 -c zip:1:9 -s Gray1:Indexed1:Gray2:Indexed2:Rgb1:Gray4:Indexed4:Rgb2:Gray8:Indexed8:Rgb4:Rgb8:stop -- psotmp.17385.img-6.parse.png psotmp.17385.img-6.sam2p-np.pdf
info: loading image from: psotmp.17385.img-6.sam2p-np.pdf
info: loading PDF from: psotmp.17385.img-6.sam2p-np.pdf
info: loaded PDF of 1681 bytes
info: separated to 5 objs + xref + trailer
info: parsed 5 objs
info: loaded PNG IDAT of 929 bytes and PLTE of 6 bytes
info: executing image converter sam2p_pr: sam2p -j:quiet -c zip:15:9 -- psotmp.17385.img-6.parse.png psotmp.17385.img-6.sam2p-pr.png
info: loading image from: psotmp.17385.img-6.sam2p-pr.png
info: loaded PNG IDAT of 1309 bytes and PLTE of 6 bytes
info: saving PNG to psotmp.17385.img-6.gray.png
info: written 1366 bytes to PNG
info: executing image converter jbig2: jbig2 -p psotmp.17385.img-6.sam2p-pr.png >psotmp.17385.img-6.jbig2
info: optimized image XObject 6 file_name=psotmp.17385.img-6.jbig2 size=257 (23%) methods=jbig2:257,parse:1091,#orig:1100,sam2p_np:1116,sam2p_pr:1557
info: saved 843 bytes (77%) on optimizable images
info: optimized 1 streams, kept 1 #orig
info: decompressed 0 /FlateDecode streams
info: compressed 1 streams, kept 0 of them uncompressed
info: saving PDF with 6 objs to: out.pso.pdf
info: generated 864 bytes (44%)
```

The problem is in `info: executing image converter jbig2: jbig2 -p psotmp.17385.img-6.sam2p-pr.png >psotmp.17385.img-6.jbig2'. The input file of this command (psotmp.17385.img-6.sam2p-pr.png) has colors green and white, but it should have black and white.

This is definitely a bug in sam2p, which needs fixing.

**Comment by pts** [comment]
Fixed in dfb1e543f0802cc1008b5c66f932e34082b51366. Please upgrade to the latest pdfsizeopt and retry.

Thank you again for reporting this bug!

**Comment by rbrito** [comment]
Sorry for the late reply, but it works wonderfully...

I will be uploading some of my changes here to a fork and, once I clean up the features that I want implemented, are you willing to consider merging them? Since my understanding of PDF files is **very**, **very** limited, I will only be doing very small changes here and there and they won't be hard to maintain (yes, I know that new features can be a burden to project maintainers, being one myself; anyway, I have been using pdfsizeopt for many years now and I don't see myself going away in the near or medium future)...

Thanks,

Rogério.

**Comment by pts** [comment]
Thank you for spending time on improving pdfsizeopt! Let's see your first change (maybe as a pull request on GitHub), and make long-term decisions later.
