### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by zvezdochiot** [pts/pdfsizeopt#121]
Can you display the default values of the options in a separate file?

**Comment by pts** [comment]
`pdfsizeopt --help` displays most of the defaults. Maintaining a separate file with the defaults would be too much maintenance work.

**Comment by zvezdochiot** [comment]
@pts say> Maintaining a separate file with the defaults would be too much maintenance work.

Ok. I thought so. But the idea is not bad?

**Comment by pts** [comment]
The idea is good, such a file would be useful. Unfortunately I don't have time to keep maintaining such a file.

**Comment by zvezdochiot** [comment]
@pts say> Unfortunately I don't have time to keep maintaining such a file.

Mark "help wanted". Someone will help (Fork=26).
