### ISSUE TITLE
lossy JPEG image optimizers (e.g. jpeg-recompress) through command line

### ISSUE THREAD

**Issue by maadjordan** [pts/pdfsizeopt#123]
Hi i tried testing lossy jpeg optimizer (near lossless) with JPEG-Recompress tool from https://github.com/danielgtaylor/jpeg-archive

i run this command with batch but its not working. 

for %i in (*.pdf) do pdfsizeopt --use-image-optimizer="jpeg-recompress %(sourcefnq)s -m smallfry -q veryhigh -p -s %(jpeg-recompress_gray_flags)s-out %(targetfnq)s" "%i" "%i.pso"

can you help on this..

Thanks.

**Comment by zvezdochiot** [comment]
I join the question and complement it. Is it possible to use instead of sam2p https://github.com/josch/img2pdf

**Comment by zvezdochiot** [comment]
@maadjordan say> Hi i tried testing lossy jpeg optimizer

See also:
* https://github.com/kud/jpegrescan (lossless)
* https://github.com/ImageProcessing-ElectronicPublications/jpegquant (lossy)

**Comment by maadjordan** [comment]
hi zvezdochiot do you know how to pass command for jpegtran or others?

**Comment by zvezdochiot** [comment]
@maadjordan say> do you know how to pass command for jpegtran or others?

No, pdfsizeopt processes only /Deflate compression. /JPXDecode and /DCTDecode it ignores.

https://github.com/pts/pdfsizeopt/blob/master/lib/pdfsizeopt/main.py:

```
7283:      if ('/JPXDecode ' in filter2 or '/DCTDecode ' in filter2):
7284:        continue
```

**Comment by maadjordan** [comment]
can processing be added to both filters /JPXDecode and /DCTDecode

**Comment by zvezdochiot** [comment]
@maadjordan say> can processing be added to both filters /JPXDecode and /DCTDecode

You can remove from line 7283 /DCTDecode:
```
7283:      if ('/JPXDecode ' in filter2):
7284:        continue
```
But this is unlikely to be handled correctly, since sam2p is used.

**Comment by maadjordan** [comment]
thanks

**Comment by pts** [comment]
Thank you for recommending jpeg-recompress and other lossy JPEG and JPEG 2000 image optimizers! Let's continue the discussion in https://github.com/pts/pdfsizeopt/issues/95 !
