### ISSUE TITLE
jbig2 failure

### ISSUE THREAD

**Issue by lemzwerg** [pts/pdfsizeopt#126]
[pdfsizeopt-jbig2 2589ca51629526374195d2e2816575bab598019c, self-compiled]
[openSUSE Leap 15.1]

Calling `jbig2 -p image.png` on the attached image produces
```
libpng warning: Application built with libpng-1.2.50 but running with 1.6.34
Error in pixReadStreamPng: png_ptr not made
Error in pixReadStream: png: no pix returned
Error in pixRead: pix not read
```
![image](https://user-images.githubusercontent.com/1630245/60810879-52515280-a18e-11e9-9f70-f4d75669aacf.png)

**Comment by zvezdochiot** [comment]
@lemzwerg say> libpng warning: Application built with libpng-1.2.50 but running with 1.6.34

/usr/include/libpng12/png.h:

 *    Binary incompatibility exists only when applications make direct access
 *    to the info_ptr or png_ptr members through png.h, and the compiled
 *    application is loaded with a different version of the library.

**Comment by pts** [comment]
Thank you for reporting this!

This can't be fixed on the pdfsizeopt side, because it's a bug in jbig2. Please report the bug there.

Please follow the Linux installation instructions on http://github.com/pts/pdfsizeopt to avoid this and similar errors.
