### ISSUE TITLE
sam2p: Bad CPU type in executable

### ISSUE THREAD

**Issue by ludoroma** [pts/pdfsizeopt#146]
i'am on macOS 10.15.7 (19H2)
i have installed following the readme procedure:
$ mkdir ~/pdfsizeopt
  $ cd ~/pdfsizeopt
  $ curl -L -o pdfsizeopt_libexec_darwin.tar.gz https://github.com/pts/pdfsizeopt/releases/download/2017-09-03d/pdfsizeopt_libexec_darwin-v1.tar.gz
  $ tar xzvf pdfsizeopt_libexec_darwin.tar.gz
  $ rm -f    pdfsizeopt_libexec_darwin.tar.gz
  $ curl -L -o pdfsizeopt.single https://raw.githubusercontent.com/pts/pdfsizeopt/master/pdfsizeopt.single
  $ chmod +x pdfsizeopt.single
  $ ln -s pdfsizeopt.single pdfsizeopt
and all gone right
but when i try to test it with
$ curl -L -o deptest.pdf https://github.com/pts/pdfsizeopt/raw/master/deptest/deptest.pdf
  $ ~/pdfsizeopt/pdfsizeopt deptest.pdf
i get a fatal error
...
info: executing image converter sam2p_np: sam2p -j:quiet -pdf:2 -c zip:1:9 -s Gray1:Indexed1:Gray2:Indexed2:Rgb1:Gray4:Indexed4:Rgb2:Gray8:Indexed8:Rgb4:Rgb8:stop -- /var/folders/zc/yvqk_h6d62s0sf8t3v4v90dw0000gn/T/psotmp.2061.img-9.parse.png /var/folders/zc/yvqk_h6d62s0sf8t3v4v90dw0000gn/T/psotmp.2061.img-9.sam2p-np.pdf
sh: /Users/ludo/pdfsizeopt/pdfsizeopt_libexec/sam2p: Bad CPU type in executable
fatal: image converter sam2p_np failed (status=0x7e00)

you know how solve?
thanks for your attention

**Comment by SebGonzalez** [comment]
Same problem, anyone has a solution ?

**Comment by zvezdochiot** [comment]
https://github.com/pts/sam2p

**Comment by SebGonzalez** [comment]
> https://github.com/pts/sam2p

There is the same problem with ghotscritpt and pngout

**Comment by pts** [comment]
The problem is that your Mac isn't able to run the 32-bit Intel x86 programs shipped with pdfsizeopt. Work to provide 64-bit Intel x86 programs is in progress: https://github.com/pts/pdfsizeopt/issues/154#issuecomment-1430746942
