### ISSUE TITLE
cannot read object with index 3 1 obj

### ISSUE THREAD

**Issue by DenKn** [pts/pdfsizeopt#156]
Hi.
After success compression I've got corrupted pdf file.
But file is very simple. You can find input.pdf and output.pdf files.

```
host:~/pdfsizeopt# ./pdfsizeopt input.pdf output.pdf
info: This is pdfsizeopt ZIP rUNKNOWN size=69734.
info: prepending to PATH: /root/pdfsizeopt/pdfsizeopt_libexec
info: loading PDF from: input.pdf
info: loaded PDF of 64094 bytes
info: separated to 43 objs + xref + trailer
info: parsed 43 objs
info: eliminated 33 unused objs, depth=4
info: found 0 Type1 fonts loaded
info: found 0 Type1C fonts loaded
info: optimized 2 streams, kept 2 zip
warning: obj 3 missing, referenced by objs [7]...
info: compressed 0 streams, kept 0 of them uncompressed
info: saving PDF with 10 objs to: output.pdf
info: trying 3 jobs and using the smallest
info: generated object stream of 455 bytes in 8 objects (27%)
info: job original generated 1580 bytes (2%)
info: job xrefstm generated 1878 bytes (3%)
info: job nostm generated 2031 bytes (3%)
info: jobs result: original=1580 xrefstm=1878 nostm=2031
info: generated 1580 bytes (2%)
```

Any ideas?
Thanks.

[output.pdf](https://github.com/pts/pdfsizeopt/files/8742238/output.pdf)
[input.pdf](https://github.com/pts/pdfsizeopt/files/8742239/input.pdf)

**Comment by zvezdochiot** [comment]
Hi @DenKn .

Use [cpdf](https://github.com/coherentgraphics/cpdf-binaries) or [qpdf](https://github.com/qpdf/qpdf) before and after using [pdfsizeopt](https://github.com/pts/pdfsizeopt).

See also #119

**Comment by DenKn** [comment]
Thanks. qpdf solved my problem.

**Comment by pts** [comment]
Thank you for reporting this bug! The attached *input.pdf* file contains an object with index `3 1 obj`, and pdfsizeopt is unable read it, beucase it supports only `N 0 obj` (with any positive N). This is indeed a bug in pdfsizeopt. Until the bug is fixed, you should preprocess the input file with *qpdf*.
