### ISSUE TITLE
whitepaper missing

### ISSUE THREAD

**Issue by andrisi** [pts/pdfsizeopt#161]
There are some refrences to a comparison between tools to make PDFs smaller, but the original URL is gone. Could you share it somewhere? Thanks a lot!

http://code.google.com/p/pdfsizeopt/downloads/detail?name=pts_pdfsizeopt2009.psom.pdf
or http://pdfsizeopt.googlecode.com/files/pts_pdfsizeopt2009.psom.pdf

https://tex.stackexchange.com/questions/19956/which-one-produces-a-pdf-with-the-smaller-file-size-pdflatex-or-latex-dvips-ps2

**Comment by pts** [comment]
Your links are outdated.

The file pts_pdfsizeopt2009.psom.pdf is linked from the official README.md of pdfsizeopt (https://github.com/pts/pdfsizeopt). The download link is https://github.com/pts/pdfsizeopt/releases/download/docs-v1/pts_pdfsizeopt2009.psom.pdf .
