### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ErmesT** [pts/pdfsizeopt#163]
Download link appears to be broken:
https://github.com/pts/pdfsizeopt/releases/download/2023-03-09/pdfsizeopt_win32exec-v8.zip

**Comment by ciampix** [comment]
let's fix it!

**Comment by hectormonacci** [comment]
`wget -O pdfsizeopt_libexec_linux.tar.gz https://github.com/pts/pdfsizeopt/releases/download/2023-03-9/pdfsizeopt_libexec_linux-v8.tar.gz
`
This is the right link (as of today).

**Comment by ErmesT** [comment]
any hope for the windows link to be updated too?

**Comment by ErmesT** [comment]
Windows link also works by removing the 0 leading the day:
https://github.com/pts/pdfsizeopt/releases/download/2023-03-09/pdfsizeopt_win32exec-v8.zip
To this:
https://github.com/pts/pdfsizeopt/releases/download/**2023-03-9**/pdfsizeopt_win32exec-v8.zip

**Comment by pts** [comment]
Fixed, thank you!
