### ISSUE TITLE
Minor issue: seemingly the default setting for use-pngout is yes

### ISSUE THREAD

**Issue by FrankEular** [pts/pdfsizeopt#17]
It seems to me that the default setting for use-pngout is yes, cf. the code
https://github.com/pts/pdfsizeopt/blob/45388b66aa97c2d699ff746919e7d645af97cf67/lib/pdfsizeopt/main.py#L6477
which seems contradict the description in readme:
https://github.com/pts/pdfsizeopt/blob/master/README.txt#L42

**Comment by pts** [comment]
Thank you for reporting this bug! I've just fixed the README.txt in 1d81f06fc5259bbeea7a2314294a1842d0560e9b.
