### ISSUE TITLE
fatal: Python version 2.4, 2.5, 2.6 or 2.7 needed

### ISSUE THREAD

**Issue by brianbuck** [pts/pdfsizeopt#174]
I'm on Python 3.12.4 and receive the message:
    fatal: Python version 2.4, 2.5, 2.6 or 2.7 needed for: C:\pdfsizeopt\pdfsizeopt.single

I was running:
    @python -v "C:\pdfsizeopt\pdfsizeopt.single" "input.pdf" "output.pdf"

Is there a way to run pdfsizeopt using a more recent version of Python?

**Comment by pts** [comment]
To run pdfsizeopt, follow the installation instructions on https://github.com/pts/pdfsizeopt .

> Is there a way to run pdfsizeopt using a more recent version of Python?

No, there isn't. As indicated by the error message, pdfsizeopt needs Python 2.4, 2.5, 2.6 or 2.7. Please note that this is an implementation detail, and most users of pdfsizeopt should not care about this. If they follow the installation instructions, pdfsizeopt will work for them.
