### ISSUE TITLE
Outdated Docker image

### ISSUE THREAD

**Issue by serl** [pts/pdfsizeopt#175]
I was trying to compress a PDF this morning, and it didn't really work.
Turns out, the issue was already identified and fixed in #160, but since I'm using pdfsizeopt in Docker and #171 is waiting, I was just using an old version.

Is there anything I can do to help?

As a workaround, this is what I did to make it work:
- Run a Docker container: `docker run --rm -it -v "$PWD:/workdir" --platform linux/amd64 ubuntu`
- Install `wget` in it: `apt update && apt install wget`
- Follow the installation instructions for Linux

**Comment by pts** [comment]
Thank you for repording this!

Fixed in 2bab16031dad854e42c2910859564d9a962bc16c.

```
latest: digest: sha256:387cd2a2938453d131dca27fbba857231d44012ae45439f1307fe46b24326140 size: 1568
```
