### ISSUE TITLE
Problem parsing PDF file

### ISSUE THREAD

**Issue by rbrito** [pts/pdfsizeopt#31]
Dear @pts,

I found a file that seems to give pdfsizeopt some headaches when parsing it. If I preprocess the file with ghostscript, qpdf or with pdftk, then pdfsizeopt can optimize it. Otherwise, it crashes with an assertion error.

Since the file is most likely "sensitive", I am sending you a link instead, but opening this issue, so that you can better organize yourself with the issue tracker.

Thanks,

Rogério.

**Comment by pts** [comment]
Thank you for reporting this!

Fixed in a41cafaac7844b0e0482e8c7430e52634e33b52f.

The error was:

```
warning: cannot parse obj 1: pdfsizeopt.main.PdfTokenParseError: X Y obj expected, got '\n1 0 obj \n<<\n/Kids [3 0 R 9 0 R ' at ofs=3424549
```
