### ISSUE TITLE
no readme

### ISSUE THREAD

**Issue by goatandsheep** [pts/pdfsizeopt#4]
How do I use this repository?

**Comment by rajat-arora** [comment]
+ 1 Can you plx upload a readme file. I really want to use your compression alg yo .....  But I don't understand how to use ya code dawg... Ya feel me..

**Comment by pts** [comment]
See some docs on code.google.com:

https://code.google.com/p/pdfsizeopt/

https://code.google.com/p/pdfsizeopt/wiki/InstallationInstructionLinux
https://code.google.com/p/pdfsizeopt/wiki/InstallationInstructionWindows

**Comment by rajat-arora** [comment]
Do you have doc's for the src?

**Comment by pts** [comment]
All the existing documentation is on https://code.google.com/p/pdfsizeopt/ or within the repository. The installation instructions contain a sample usage command-line. If the provided command-line doesn't work for you please let me know.
