### ISSUE TITLE
File with duplicate objects

### ISSUE THREAD

**Issue by rbrito** [pts/pdfsizeopt#42]
I just came across a few files that pdfsizeopt refuses to process. They are available at:

https://www.maa.org/sites/default/files/pdf/upload_library/22/Ford/Cohn.pdf
https://www.maa.org/sites/default/files/pdf/upload_library/22/Ford/Wilson.pdf
https://www.maa.org/sites/default/files/pdf/upload_library/22/Ford/HLAlder.pdf

They are probably defective, but atril/evince shows them (apparently) without any glitches.

**Comment by pts** [comment]
Thank you very much for reporting this! Fixed all 3 PDFs in 818ccd9c809d4788b7425a82c7aecf282418cd3d. In fact, all of them were broken, because they contained extra whitespace in front of the `xref`. I've made pdfsizeopt more lenient and ignore that whitespace.
