### ISSUE TITLE
Another file with a blank page

### ISSUE THREAD

**Issue by rbrito** [pts/pdfsizeopt#44]
Dear @pts,

Packt is a publisher that releases for free one ebook each day. One of their recent freebies, "Android Design Patterns", after being processed with pdfsizeopt, gets a blank cover (i.e., page 1).

Unfortunately, extracting the first page with pdftk and processing only that page it makes the problem go away, which is why I am unable to attach it here.

I am sending you a link to the entire file in private, so that you can see what may be wrong with it.

Thanks,

Rogério.

**Comment by pts** [comment]
Thank you for reporting this! The first page works for me with the latest pdfsizeopt.
