### ISSUE TITLE
a blank image because its /SMask image doesn't have /ColorSpace /DeviceGray

### ISSUE THREAD

**Issue by rbrito** [pts/pdfsizeopt#45]
(The image in p058.pso.pdf is blank only in Evince. It appears in Chrome 61 and Ghostscript.)

I just discovered another file that, after being processed with pdfsizeopt, gives a blank image where it is not supposed to. Since I don't know if this is the same bug as the one I reported previously, I am attaching it here.

[p058.pdf](https://github.com/pts/pdfsizeopt/files/1323515/p058.pdf)

If I interrupt the script with an `assert False` right before the comment `# Optimize images.` around line 7044 of main.py, the PNG file that I get is, indeed, a blank one, which I attach here for your reference:

![psotmp 10341 img-21 parse](https://user-images.githubusercontent.com/212145/30730529-299471dc-9f3e-11e7-9d4d-7f4f42f4ab99.png)

This is from a book from O'Reilly. I can try to find an URL for this and, if I am successful, I can post it here. Otherwise, I can send you a copy of this, if you so wish.

**Comment by pts** [comment]
Thank you for reporting this! It works perfectly for me with the newest pdfsizeopt. See the output file below.

[p058.pso.pdf](https://github.com/pts/pdfsizeopt/files/1333686/p058.pso.pdf)

**Comment by rbrito** [comment]
Hi, @pts.

On Tue, Sep 26, 2017 at 12:18 PM, Péter Szabó <notifications@github.com> wrote:
> Thank you for reporting this! It works perfectly for me with the newest pdfsizeopt. See the output file below.
>
> [p058.pso.pdf](https://github.com/pts/pdfsizeopt/files/1333686/p058.pso.pdf)

I also see a blank image on this page as well. I suspect that the
problem here is also (as I mentioned to you via private email) with
poppler, though.

Thanks for providing *your* output after a run of pdfsizeopt.


Thanks,

Rogério.

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by pts** [comment]
This needs further investigation. p058.pso.pdf works with Ghostscript and Chrome 61, but the image doesn't appear with Evince (most probably using libpoppler44). Evince displays this error 4 times: `Syntax Error (370956): Bad image parameters`.

**Comment by pts** [comment]
The rule is: if image A has an `/SMask` referring to image S, then image S must have `/ColorSpace /DeviceGray`.

Before d193af75b897aa01e9ba48b7a54416abb7975fd6 there was a bug in pdfsizeopt which violated this rule in the output of pdfsizeopt. The bug prevented the detection `/SMask` in some images (e.g. with `/Filter /DCTDecode`), so pdfsizeopt incorrectly optimized some S images to without `/ColorSpace /DeviceGray`.
