### ISSUE TITLE
Missing glyphs when running pdfsizeopt

### ISSUE THREAD

**Issue by rbrito** [pts/pdfsizeopt#54]
Dear @pts,

I'm getting a problem with pdfsizeopt (commit 5df85c37e2213c4731c149999c66eae002456972) with a few PDF files. They are not numerous, but I found them here and there. After being processed with pdfsizeopt, there are missing glyphs. In particular, ligatures seem to be missing.

Here is one page of the offending PDF: [out-003.pdf](https://github.com/pts/pdfsizeopt/files/1377351/out-003.pdf)

Here is what I get when I run diffpdf: 
![screenshot at 2017-10-11 19-10-02](https://user-images.githubusercontent.com/212145/31469526-4c679dd6-aeb8-11e7-8007-c8e769da729d.png)

Thanks,

Rogério Brito.

**Comment by pts** [comment]
Thank you for reporting this! Fixed in ca01151da5c20edfb9ba929b3fc606a237ffc23a.

This is related to https://github.com/pts/pdfsizeopt/issues/50, that fix wasn't good enough, this fix does what's needed.

**Comment by rbrito** [comment]
Thanks a lot. It seems to work now.
