### ISSUE TITLE
pdfsizeopt reduced less then 1 MB

### ISSUE THREAD

**Issue by joaolm** [pts/pdfsizeopt#58]
Hi, i have a scanned PDF of 23 MB (72 pages) and pdfsizeopt reduced it to 22,5 MB.
I can't send the file because it has sensitive information.
Follows attached some info from identify command (Ubuntu 16.04).
[identify.txt](https://github.com/pts/pdfsizeopt/files/1421762/identify.txt)
.

**Comment by pts** [comment]
It can happen that the size reduction for some PDFs is small. For example, if you run pdfsizeopt on the output of pdfsizeopt, you won't get any additional size reduction.

You can run `pdfsizeopt --stats filename.pdf` on both the input and output of pdfsizeopt, to see a size breakdown by object type.

I can do a more specific analysis only if you attach the PDF file. Maybe you can remove the sensitive information first.
