### ISSUE TITLE
Win7 "'import site' failed" 

### ISSUE THREAD

**Issue by JamesLarkinWhite** [pts/pdfsizeopt#59]
I have used your software without issues on a Linux mashine. Now i am on Win 7 64 bit on my office PC and i get the following error when i start it ( i use the most up to date realese):

`'import site' failed; use -v for traceback
Could not import runpy module`

Python is located in `C:\Program Files (x86)\Python27` and it is also in the windows PATH.

**Comment by pts** [comment]
Thank you for reporting this!

pdfsizeopt should work on Windows according to the instructions, and it works for me using Wine on Linux. (I don't have easy access to a Windows 7 machine to try.) I need more input from you to diagnose and fix this issue.

Have you been following the Windows installation instructions on http://github.com/pts/pdfsizeopt? Please delete `C:\pdfsizeopt`, and reinstall from scratch, following the instructions, and then copy-paste the entire contents of the Command Prompt window when you are trying to run pdfsizeopt.

Maybe there is an environment variable which confuses pdfsizeopt. You may try to unset all environment variables with `PYTHON` in their name. (Run the `set` command to list environment variables, and set them to empty, e.g. `set PYTHONSTARTUP=`, and then run pdfsizeopt).

Please note that it's not necessary to install Python first, and pdfsizeopt doesn't use the Python you have installed (but it uses its own `pdfsizeopt_win32exec\pdfsizeopt_python.exe`).

**Comment by pts** [comment]
Do you get the `'import site' failed` error even with this command? What does this command display?
```
pdfsizeopt_win32exec\pdfsizeopt_python.exe -E pdfsizeopt.single
```

**Comment by pts** [comment]
Closing this issue until I get the data I asked.
