### ISSUE TITLE
Docker image missing image optimizers

### ISSUE THREAD

**Issue by Schabernack** [pts/pdfsizeopt#64]
Trying to use additional image optimizers on macosx with docker yields the following error.

```
nmn@wernstrom ~/Documents/cic/PR/passport $ docker run -v "$PWD:/workdir" -u "$(id -u):$(id -g)" --rm -it ptspts/pdfsizeopt pdfsizeopt --use-image-optimizer=optipng,jbig2,zopflipng,advpng,ECT  foo.pdf output_compressed.pdf
info: This is pdfsizeopt ZIP rUNKNOWN size=66765.
info: prepending to PATH: /usr/bin
error: image optimizer not found on PATH: optipng
error: image optimizer not found on PATH: zopflipng
error: image optimizer not found on PATH: advpng
error: image optimizer not found on PATH: ECT
```

Maybe image optimizers can be added to docker image into PATH by default?

**Comment by pts** [comment]
Thank you for the suggestion!

To avoid extra maintenance costs, only the standard image optimizers (sam2p, jbig2 and pngout) are included in the official Docker image so far. Feel free to create your Docker image based on *ptspts/pdfsizeopt*, and include the image optimizers you need. Once done, please add the name of your Docker image as a comment to this issue. (As an alternative, please send a donation.)

**Comment by pts** [comment]
Implemented in https://github.com/pts/pdfsizeopt/commit/7534c0fc227b6cebca7bd85cdfae39065346ff18.

Another docker image, *ptspts/pdfsizeopt-with-extraimgopt* was created. Run it as:
```
$ docker run -v "$PWD:/workdir" -u "$(id -u):$(id -g)" --rm -it ptspts/pdfsizeopt-with-extraimgopt pdfsizeopt --use-image-optimizer=sam2p,jbig2,pngout,zopflipng,optipng,advpng,ECT input.pdf output.pdf
```

**Comment by Schabernack** [comment]
Amazing. Thanks @pts .
