### ISSUE TITLE
Please add license statements for pdfsizeopt

### ISSUE THREAD

**Issue by rbrito** [pts/pdfsizeopt#65]
Dear Péter,

For people that plan on package your tool, it is necessary to know what kind of license you use for pdfsizeopt. It would be important to have, at least, a license file at the top level of the repository. Fortunately, github makes this easy to implement with just a few clicks:

https://help.github.com/articles/adding-a-license-to-a-repository/

From the file `lib/pdfsizeopt/main.py`, I can see that your intented license is the GPLv2+.

(Great choice, BTW! 😄)

Thanks,

Rogério Brito.

**Comment by rbrito** [comment]
From a Debian point of view, there's an automated tool called `licensecheck` and, when run at the top level of the repository, gives, as output, the attached file. Every Debian package has to have a file called `copyright` associated with it (usually, at `/usr/share/doc/<package-name>/copyright`.

Here follows the output of `licensecheck -r --merge-licenses --deb-fmt --deb-machine . > copyright.txt` (the txt extension is because github doesn't allow arbitrary files to be attached).

[copyright.txt](https://github.com/pts/pdfsizeopt/files/1514728/copyright.txt)

**Comment by pts** [comment]
LICENSE file added in 81b8a194c3ad0efbf45d7ee8d8b8c12392ece6bd.

I hesitate to add additional license statements to other files, I don't want to pollute them.

**Comment by rbrito** [comment]
OK, great. Just to make things clear: the license is GPLv2 only or GPLv2+?

**Comment by pts** [comment]
The file LICENSE file contains a copy of GPLv2, the license is GPLv2+.

**Comment by rbrito** [comment]
Thanks.
