### ISSUE TITLE
Temporary files created in a specific .cache folder

### ISSUE THREAD

**Issue by sbibauw** [pts/pdfsizeopt#72]
Currently temporary files (`psotmp.*.tmp.*`) created by `pdfsizeopt` are visible, in the working directory and can be there for a long time when processing a very big PDF with pngout taking so long. For instance, I currently have more than 1900 tmp files. This is totally cluttering the working directory, and since this directory is in my Dropbox folder, it is being uselessly synced by Dropbox... I would suggest having another default behavior, using a fixed cache directory.

A simple solution on all Unix systems could be to create a `~/.cache/pdfsizeopt/` directory.

**Comment by pts** [comment]
This is a very reasonable suggestion, thank you for suggesting it! Fixed it in 0ff16054ba7af0255da01b16942c1765ad2f6088.

Please note that the default will remain the output file directory, so if you want to use a specific directory, use `pdfsizeopt --tmp-dir=...` or environment variable *TMPDIR* (or *TEMP* on Windows).
