### ISSUE TITLE
Bug (probably because of generating a broken ps tmp file)

### ISSUE THREAD

**Issue by FrankEular** [pts/pdfsizeopt#8]
bok%3A978-3-642-76235-2.pdf is uploaded here: https://www.dropbox.com/s/fovle3bx2hz0o0o/bok%253A978-3-642-76235-2.pdf?dl=0

WARNING: The ebook is personally used and uploaded ONLY for debugging. It's NOT authorized to publicize it to anywhere else.

 % pdfsizeopt bok%3A978-3-642-76235-2.pdf 
info: This is pdfsizeopt rUNKNOWN size=329129.
info: using Java for Multivalent: /usr/bin/java
info: loading PDF from: bok%3A978-3-642-76235-2.pdf
info: loaded PDF of 41970242 bytes
info: separated to 4315 objs + xref + trailer
info: found 8 Type1 fonts loaded
info: writing Type1CConverter (286830 font bytes) to: psotmp.4296.conv.tmp.ps
info: using Ghostscript gs: GPL Ghostscript 9.06 (2012-08-08)
info: executing Type1CConverter with Ghostscript: gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dPDFSETTINGS=/printer -dColorConversionStrategy=/LeaveColorUnchanged -sOutputFile=psotmp.4296.conv.tmp.pdf -f psotmp.4296.conv.tmp.ps
Type1CConverter: using interpreter GPL Ghostscript 906 20120808
Type1CConverter: converting font /Times-Roman to /Obj0000000015
Type1CConverter: converting font /Helvetica to /Obj0000000029
Type1CConverter: converting font /Times-Italic to /Obj0000000055
Type1CConverter: converting font /Times-Bold to /Obj0000000068
Type1CConverter: converting font /HelveticaBold to /Obj0000000185
Error: /undefined in --get--
Operand stack:
   --nostringval--   --dict:2/100(ro)(L)--   invalidfileaccess   --dict:30/32(L)--   MultipleFontsDefined
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1910   1   3   %oparray_pop   1909   1   3   %oparray_pop   1893   1   3   %oparray_pop   1787   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--
Dictionary stack:
   --dict:1169/1684(ro)(G)--   --dict:0/20(G)--   --dict:92/200(L)--
Current allocation mode is local
Current file position is 219634
GPL Ghostscript 9.06: Unrecoverable error, exit code 1
info: Type1CConverter failed, status=0x100
Traceback (most recent call last):
  File "/home/gaussfrank/pdfsizeopt.try/pdfsizeopt", line 30, in <module>
    sys.exit(main.main(sys.argv))
  File "/home/gaussfrank/pdfsizeopt.try/lib/pdfsizeopt/main.py", line 8218, in main
    pdf.ConvertType1FontsToType1C()
  File "/home/gaussfrank/pdfsizeopt.try/lib/pdfsizeopt/main.py", line 5341, in ConvertType1FontsToType1C
    TMP_PREFIX + 'conv.tmp.ps', TMP_PREFIX + 'conv.tmp.pdf')
  File "/home/gaussfrank/pdfsizeopt.try/lib/pdfsizeopt/main.py", line 5065, in GenerateType1CFontsFromType1
    assert False, 'Type1CConverter failed (status)'
AssertionError: Type1CConverter failed (status)

**Comment by pts** [comment]
Thank you for reporting this bug! I was able to reproduce it based on the instructions provided.

Unfortunately the bug is hard to fix, so all I can offer now is a workaround:

$ pdfsizeopt --do-optimize-fonts=false bok%3A978-3-642-76235-2.pdf

Here is the smallest output PDF file I could get with pdfsizeopt (32358362 bytes, 77% of the original):

https://www.dropbox.com/s/sw6vhxto24iijfv/bok%253A978-3-642-76235-2.psom.pdf?dl=0

**Comment by pts** [comment]
You may want to rerun this file with the latest version of pdfsizeopt, it should work now. (See https://github.com/pts/pdfsizeopt/issues/16 for details.)

Please note that `--do-optimize-fonts=false` is not needed now, since the newest version of pdfsizeopt is able to process this strange font file.
