### ISSUE TITLE
AssertionError: duplicate obj 20

### ISSUE THREAD

**Issue by rbrito** [pts/pdfsizeopt#80]
Dear @pts,

I have a PDF file here that, when processed with pdfsizeopt, gives me the following error:

```
$ ~/Downloads/pdfsizeopt/pdfsizeopt --use-image-optimizer=jbig2 server-based-java-programming.pdf 
info: This is pdfsizeopt rUNKNOWN size=392193.
info: prepending to PATH: /home/rbrito/Downloads/pdfsizeopt
info: loading PDF from: server-based-java-programming.pdf
info: loaded PDF of 10280791 bytes
warning: problem with xref table: startxref+%%EOF not found
warning: trying to load objs without the xref table
Traceback (most recent call last):
  File "/home/rbrito/Downloads/pdfsizeopt/pdfsizeopt", line 41, in <module>
    sys.exit(main.main(sys.argv, script_dir=script_dir))
  File "/home/rbrito/Downloads/pdfsizeopt/lib/pdfsizeopt/main.py", line 9462, in main
    ).Load(file_name)
  File "/home/rbrito/Downloads/pdfsizeopt/lib/pdfsizeopt/main.py", line 4535, in Load
    do_ignore_generation_numbers=self.do_ignore_generation_numbers)
  File "/home/rbrito/Downloads/pdfsizeopt/lib/pdfsizeopt/main.py", line 5055, in ParseWithoutXref
    'duplicate obj %d' % prev_obj_num)
AssertionError: duplicate obj 20
```

Actually, this is not the only file that I have that shows this kind of error (I may have to hunt the other files, though). While it is probably damaged (see the two warnings emitted), all the PDF viewers that I could use show the file without any (visible) problem and, if I preprocess it with either qpdf or with pdftk (they probably discard something), pdfsizeopt can work correctly with it.

I also tried commenting that assert and it apparently worked, but I am not sure if that is a prudent solution or even if what the viewers do is the correct thing.

Since this is copyrighted, I am sending you the URL of this file by email. If you prefer me to encrypt things like the other user did, please let me know and I will do it.

Thanks,

Rogério.

**Comment by pts** [comment]
Thank you for reporting this! Fix it in 00b10b79f0958e60593de85dcb46c25ad2286864.

The bug was caused by a few garbage bytes near the end of the PDF file, after %%EOF. The fix is to ignore those garbage bytes. Please note that the input PDF is broken (because %%EOF should be at the end.)
