### ISSUE TITLE
pdfsizeopt.main.PdfMissingRootError: /Root reference not found in trailer.

### ISSUE THREAD

**Issue by rbrito** [pts/pdfsizeopt#86]
Hi, @pts.

I collected a few PDFs more that aren't processed by pdfsizeopt. Two of them have, curiously, have the `Producer:` field (according to pdfinfo) as some Acrobat programs.

Here are them:

[Notas_de_Algebra_Lineal-Ibort-Rodriguez.pdf](https://github.com/pts/pdfsizeopt/files/1909895/Notas_de_Algebra_Lineal-Ibort-Rodriguez.pdf)
[Notes_from_Trigonometry-Butler.pdf](https://github.com/pts/pdfsizeopt/files/1909896/Notes_from_Trigonometry-Butler.pdf)

I have another one (produced by Acrobat distiller) that shows the same error, but that one is copyrighted and I can send you privately if you want.

Thanks for all your help,

Rogério.

**Comment by pts** [comment]
```
$ ../pdfsizeopt --use-pngout=no Notes_from_Trigonometry-Butler.pdf 
info: This is pdfsizeopt rUNKNOWN size=392117.
info: prepending to PATH: ../pdfsizeopt_libexec
info: loading PDF from: Notes_from_Trigonometry-Butler.pdf
info: loaded PDF of 1451008 bytes
warning: problem with xref table: startxref+%%EOF not found
warning: trying to load objs without the xref table
info: separated to 800 objs + trailer
Traceback (most recent call last):
  File "../pdfsizeopt", line 41, in <module>
    sys.exit(main.main(sys.argv, script_dir=script_dir))
  File "../lib/pdfsizeopt/main.py", line 9470, in main
    ).Load(file_name)
  File "../lib/pdfsizeopt/main.py", line 4577, in Load
    raise PdfMissingRootError('/Root reference not found in trailer.')
pdfsizeopt.main.PdfMissingRootError: /Root reference not found in trailer.
```

The relevant error message is:

```
warning: problem with xref table: startxref+%%EOF not found
```

These files contain more than 128 bytes of junk at the end. I've increased the limit to 400.

If you believe that these files are valid PDF, or you have any insights on how other tools process them even though they are invalid, please let me know. (Maybe it's OK to have junk at the end of linearized PDF.)
