### ISSUE TITLE
Add native support for pngwolf-zopfli

### ISSUE THREAD

**Issue by squinky86** [pts/pdfsizeopt#87]
Problem: Distributing pdfsizeopt with pngout means bundling the program with non-free, closed-source software. pdfsizeopt should take advantage of other open-source projects, like pngwolf, as the default for png optimization rather than pngout.

Using the attached .pdf file (created by the completely random .pngs from http://r0k.us/graphics/kodak/ and the attached .tex file), the following results were obtained:

- [test.pdf](https://github.com/pts/pdfsizeopt/files/1921124/test.pdf)
- [test.pngout.pdf](https://github.com/pts/pdfsizeopt/files/1921130/test.pngout.pdf)
- [test.pngwolf.pdf](https://github.com/pts/pdfsizeopt/files/1921178/test.pngwolf.pdf)
- [test.tex.txt](https://github.com/pts/pdfsizeopt/files/1921234/test.tex.txt)

```
$ du -b test.pdf
17705411        test.pdf
$ time pdfsizeopt test.pdf #default using pngout
(output truncated)
info: generated 14997954 bytes (85%)

real    3m26.993s
user    1m45.506s
sys     0m10.371s
$ mv test.pso.pdf test.pngout.pdf
$ time pdfsizeopt --use-pngout=false --use-image-optimizer="pngwolf --in=%(sourcefnq)s --out=%(targetfnq)s" test.pdf
(output truncated)
info: generated 14538414 bytes (82%)

real    6m36.005s
user    7m40.526s
sys     0m39.127s
$ mv test.pso.pdf test.pngwolf.pdf
```
The test files are attached. Also, I ran the output through pdfsizeopt again to see how compressed it gets with a combination of pngwolf and pngout in parallel. test.pngout.pngwolf.pdf runs pngout, then pngwolf. test.pngwolf.pngout.pdf runs pdfwolf, then pngout. These results didn't produce any decrease in size; only running pngwolf was sufficient to encompass all the benefits of pngout plus some:

```
$ du -b test*.pdf
17705411        test.pdf
14997954        test.pngout.pdf
14538414        test.pngout.pngwolf.pdf
14538414        test.pngwolf.pdf
14538414        test.pngwolf.pngout.pdf
```

**Comment by pts** [comment]
Thank you for suggesting this, and thank you for doing the size and time measurements!

As of 60b9a1aea2b820521a9deae0afd1177445c976f4, pdfsizeopt supports the short invocation `--use-image-optimizer=pngwolf`.

I've created https://github.com/pts/pdfsizeopt/issues/88 to track the progress of replacing pngout with something else by default. Your insights on that issues are very much appreciated.

FYI My test.pngout.pdf is larger (see detals in https://github.com/pts/pdfsizeopt/issues/88).
