### ISSUE TITLE
Merging subsetted fonts

### ISSUE THREAD

**Issue by teepeemm** [pts/pdfsizeopt#9]
I have a XeLaTeX document that is including the same font multiple times, and I'm trying to merge those subsets.  If I have
```TeX
\documentclass{article}
\begin{document}
sub document page 1
\end{document}
```
and
```TeX
\documentclass{article}
\usepackage{pdfpages}
\begin{document}
main document page 1
\includepdf{subdocument}
\end{document}
```
and compile both with XeLaTeX, the main document has the fonts GJZFOO+CMR10 and EKQAMG+CMR10 (according to the command pdffonts).  If I then run
`python pdfsizeopt --use-multivalent=no --use-pngout=no --use-jbig2=no pdffonts.pdf `
I see (among other output)
`info: merged fonts ['/EKQAMG+CMR10', '/GJZFOO+CMR10'], reduced char count from 29 to 16 (55%)`
but the resulting document still has both fonts.  Am I missing something?  Shouldn't the two subsets be merged into one?  Or is that actually happening, and I'm misinterpreting the information?

This sounds related to [this google code archive issue](https://code.google.com/archive/p/pdfsizeopt/issues/89), which was closed for lack of input.

I've attached the reduced pdf, if that helps things.
[pdffonts.pso.pdf](https://github.com/pts/pdfsizeopt/files/696653/pdffonts.pso.pdf)

**Comment by pts** [comment]
Thank you for filing the bug, and thank you for posting a small example which is easy to understand! Please attach the original pdffonts.pdf file as well so that I can investigate further.

What makes you think that the attached pdffonts.pso.pdf font has the same font twice? I was able to find only one font inside. Please double check.

**Comment by teepeemm** [comment]
Mac OS X 10.11.6 has the command line tool pdffonts (version 0.46.0).  Running that on the unreduced pdf, I get the output
```
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
GJZFOO+CMR10                         Type 1C           Builtin          yes yes no       4  0
EKQAMG+CMR10                         Type 1C           Builtin          yes yes no      12  0
```
Afterward, the only output is nearly identical:
```
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
GJZFOO+CMR10                         Type 1C           Builtin          yes yes no       6  0
EKQAMG+CMR10                         Type 1C           Builtin          yes yes no      12  0
```

This seems to be saying that both files have two fonts, each a subset of CMR10.  Could pdffonts be misinterpreting the font information?  Or could I be misinterpreting what pdffonts is saying?  I've attached the original pdf.
[pdffonts.pdf](https://github.com/pts/pdfsizeopt/files/699748/pdffonts.pdf)

**Comment by pts** [comment]
Indeed, the `pdffonts` tool doesn't display the number of fonts correctly. It displays object numbers 6 and 12, both of which are small, and contain a reference of the single font object 11. So `pdfsizeopt` works as intended in this case.
