### ISSUE TITLE
request: new release binaries

### ISSUE THREAD

**Issue by hannob** [pts/pdfsizeopt#90]
The current binary releases (I care about the ones for Linux, but same is true for others) are more than a year old. Several fixes have happened since then, so I wanted to ask if we could have new release binaries.

**Comment by pts** [comment]
It's true that the new release binaries are more then a year old, but they are still up to date. In general, if you follow the install instructions on https://github.com/pts/pdfsizeopt , you will get the latest software. If this is not true for you, please let me know which update you are not getting.
