### ISSUE TITLE
Font bug even with --do-unify-fonts=no --do-regenerate-all-fonts=no

### ISSUE THREAD

**Issue by wilbowma** [pts/pdfsizeopt#93]
Here's an example PDF: https://williamjbowman.com/downloads/paper.pdf
And it's output, when run with the following command: https://williamjbowman.com/downloads/paper.pso.pdf

```
/usr/bin/pdfsizeopt --do-unify-fonts=no --do-regenerate-all-fonts=no --do-double-check-type1c-output=yes --use-jbig2=yes --use-image-optimizer="ect -9 -strip -progressive --mt-deflate %(targetfnq)s" paper.pdf
```

Notice that certain characters, like `*` in the title, and like ligatures in the copyright block, are replaced by some default character.

Version info:
```
> pdfsizeopt --version
info: This is pdfsizeopt ZIP rUNKNOWN size=66137.
> uname -a
Linux letai 4.17.2-1-ARCH #1 SMP PREEMPT Sat Jun 16 11:08:59 UTC 2018 x86_64 GNU/Linux
```

**Comment by pts** [comment]
Thank yo for reporting this bug!

I'm not able to reproduce this bug with the latest pdfsizeopt, my output looks correct ([paper.pso.pdf](https://github.com/pts/pdfsizeopt/files/2201715/paper.pso.pdf)) with

```
info: This is pdfsizeopt ZIP rUNKNOWN size=68657.
```

Please upgrade the the latest pdfsizeopt (installation instructions on https://github.com/pts/pdfsizeopt/). If you are still experiencing problems, please report them in this issue, also copy-pasting the full console output of pdfsizeopt.

**Comment by wilbowma** [comment]
My fault; after updating to `git HEAD` the problem has disappeared.
